# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name deve.cliniquess.ca;
    return 301 https://$host$request_uri;
}

# HTTPS - WordPress
server {
    listen 443 ssl http2;
    server_name deve.cliniquess.ca;

    root /var/www/clinique-website;
    index index.php index.html index.htm;

    # SSL Certbot
    ssl_certificate /etc/letsencrypt/live/deve.cliniquess.ca/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/deve.cliniquess.ca/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # Logs
    access_log /var/log/nginx/cliniquess_access.log;
    error_log /var/log/nginx/cliniquess_error.log;

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt { log_not_found off; access_log off; allow all; }
    location ~* \.(css|gif|ico|jpeg|jpg|js|png|svg|woff|woff2|ttf|otf|eot)$ {
        expires max;
        log_not_found off;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
